### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by TwinMist** [NuffZetPand0ra/cli-countdown#1]
Problem 1
    - Installation request for nuffy/cli-countdown ^0.1.2 -> satisfiable by nuffy/cli-countdown[v0.1.2].
    - nuffy/cli-countdown v0.1.2 requires nesbot/carbon dev-master -> satisfiable by nesbot/carbon[dev-master] but these conflict with your requirements or minimum-stability.

any ideas how to resolve?

thanks

**Comment by NuffZetPand0ra** [comment]
Sorry, was not an issue in the project I made the plugin for. Fixed in https://github.com/NuffZetPand0ra/cli-countdown/releases/tag/v0.1.2.1

**Comment by TwinMist** [comment]
Sill not working
  Problem 1
    - Installation request for nuffy/cli-countdown v0.1.2.1 -> satisfiable by nuffy/cli-countdown[v0.1.2.1].
    - nuffy/cli-countdown v0.1.2.1 requires nesbot/carbon dev-master -> satisfiable by nesbot/carbon[dev-master] but these conflict with your requirements or minimum-stability.
